application:
  app:
    host: "${APP_HOST:http://localhost}"
    name: "${APP_NAME:kibvet}"
    port: "${APP_PORT:8080}"
  security:
    jwt:
      secret-key: zdtlD3JK56m6wTTgsNFhqzjqP
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days

server:
  port: "${APP_PORT:8080}"

app:
  name: "${APP_NAME:kibvet}"



springdoc:
  show-actuator: false
  writer-with-default-pretty-printer: true
  pre-loading-enabled: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

error:
  handling:
    exception-logging: with_stacktrace
    http-status-in-json-response: true

spring:
  application:
    name: "${APP_NAME:kibvet}"
  security:
    user:
      name: ${SERVER_USER:user}
      password: ${SERVER_PASSWORD:password}
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    driverClassName: com.p6spy.engine.spy.P6SpyDriver
  jpa:
    open-in-view: true
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.PostgreSQLDialect"
        jdbc:
          time_zone: "UTC"
          lob:
            non_contextual_creation: true
    hibernate:
      ddl-auto: none
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: io.hypersistence.utils.hibernate.naming.CamelCaseToSnakeCaseNamingStrategy

management:
  tracing:
    sampling:
      probability: 1.0
  endpoint:
    health:
      show-details: always
      show-components: always
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  level:
    org.springframework.context.support.PostProcessorRegistrationDelegate: OFF
  pattern:
    console: "${LOG_PATTERN:%boldMagenta([%thread]) %cyan(%date) %highlight(%-5level) %green([%logger{36}:%line]) : %msg%n}"
  charset:
    console: UTF-8